/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Mofa extends javax.swing.JFrame {

    /**
     * Creates new form Mofa
     */
    public Mofa() {
        initComponents();
        
        getConnection();
        Show_employee();
    }
    
     public Connection getConnection(){
        
   Connection con=null;
        
       
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/itp?useSSL=true", "root", "");
            //JOptionPane.showMessageDialog(null, "Connected to database");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
               
    
    }
     
     
     public ArrayList<Products> getproductsList(){
            ArrayList<Products> productsList=new ArrayList<Products>();
            Connection con=getConnection();
            String query="SELECT * from mofa_info";
            
            Statement st;
            ResultSet rs;
        
        
            
        
        try {
            
            st=con.createStatement();
            rs=st.executeQuery(query);
            Products products;
            
            while(rs.next()){
            
                
                products=new Products(rs.getInt("aid"),rs.getString("name"),rs.getString("provice"),rs.getString("product"),rs.getString("grade"),Float.parseFloat(rs.getString("price")),Float.parseFloat(rs.getString("qty")),Float.parseFloat(rs.getString("total")));
                productsList.add(products);
                
            
            
            }
            
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(Level.SEVERE, null, ex);
        }
        return productsList;
            
             
            
            
            
        
    
    
    }
     
     public void Show_employee(){
        
        ArrayList<Products> list=getproductsList();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    
        
        model.setRowCount(0);
        Object[] row=new Object[10];
        for(int i=0;i<list.size();i++){
        
                row[0]=list.get(i).getId();
                row[1]=list.get(i).getName();
                row[2]=list.get(i).getProvince();
                row[3]=list.get(i).getProduct();
                row[4]=list.get(i).getGrade();
                row[5]=list.get(i).getQty();
                row[6]=list.get(i).getAmount();
                
                
                model.addRow(row);
        
        }
    
    
    }
     
      
    public void ShowEmployee(int index){
        
            txt_id.setText(Integer.toString(getproductsList().get(index).getId()));
            txt_name.setText(getproductsList().get(index).getName());
            txt_province.setText(getproductsList().get(index).getProvince());
            //txt_product.setText(Integer.toString(getEmployeeList().get(index).getAge()));        
            txt_product.setText(getproductsList().get(index).getProduct());
            txt_grade.setText(getproductsList().get(index).getGrade());
            
            txt_amount.setText(Float.toString(getproductsList().get(index).getPrice()));
            txt_qty.setText(Float.toString(getproductsList().get(index).getQty()));
            txt_total.setText(Float.toString(getproductsList().get(index).getAmount()));
     
        
    
    
    
    
    
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        txt_province = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txt_product = new javax.swing.JTextField();
        txt_grade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agent Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 260, 150, 28);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_name);
        txt_name.setBounds(250, 250, 340, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Province:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 330, 110, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agent ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 190, 110, 28);

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id);
        txt_id.setBounds(250, 180, 340, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biofood logo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 20, 160, 140);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 420, 100, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(117, 500, 73, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount per Kilo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(770, 170, 210, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity(kg)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(830, 250, 150, 40);
        jPanel1.add(txt_amount);
        txt_amount.setBounds(1000, 170, 200, 40);
        jPanel1.add(txt_qty);
        txt_qty.setBounds(1000, 250, 200, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 620, 130, 50);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 620, 130, 50);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 730, 130, 50);

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Print");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(290, 730, 130, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDl", "Name", "Province", "Product", "Grade", "Quantity", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(770, 330, 830, 420);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1520, 780, 130, 50);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1240, 180, 180, 40);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setText("Calculate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1470, 250, 150, 50);

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total);
        txt_total.setBounds(1460, 180, 180, 40);

        txt_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provinceActionPerformed(evt);
            }
        });
        txt_province.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_provinceKeyPressed(evt);
            }
        });
        jPanel1.add(txt_province);
        txt_province.setBounds(250, 320, 340, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 320, 340, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 320, 340, 40);

        txt_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_productKeyPressed(evt);
            }
        });
        jPanel1.add(txt_product);
        txt_product.setBounds(250, 400, 340, 40);
        jPanel1.add(txt_grade);
        txt_grade.setBounds(250, 490, 340, 40);

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 50)); // NOI18N
        jLabel11.setText("MARGINALIZED ORGANIC PRODUCERS' ASSOCIATION");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 30, 1390, 70);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Grades");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(600, 490, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pwr.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 160, 1680, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          MessageFormat header=new MessageFormat("M.O.P.A"); 
        MessageFormat footer=new MessageFormat("Biofood International");
        
        
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header,footer);
        } catch (java.awt.print.PrinterException ex) {
            //Logger.getLogger(Employee_Info1.class.getName()).log(Level.SEVERE, null, ex);
            
            JOptionPane.showMessageDialog(null, "Cannot be Print!"+ex.getMessage());
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
        Connection con=getConnection();
        PreparedStatement ps=con.prepareStatement("INSERT INTO mofa_info(name,provice,product,grade,price,qty,total)" + "values(?,?,?,?,?,?,?)");
                ps.setString(1, txt_name.getText());
        ps.setString(2, txt_province.getText());
        ps.setString(3, txt_product.getText());
        ps.setString(4, txt_grade.getText());
        ps.setString(5, txt_amount.getText());
        ps.setString(6, txt_qty.getText());
        ps.setString(7, txt_total.getText());
        
        
        ps.executeUpdate();
        Show_employee();
        
        
        
       // ps.setString(8, txt_sal.getText());
        
        
        JOptionPane.showMessageDialog(null, "Data Saved!");
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                String UpdateQuery= null;
                PreparedStatement ps=null;
                
        
        
            try {
                
                
                Connection con=getConnection();
                UpdateQuery="UPDATE mofa_info SET name=?,provice=?,product=?,grade=?,price=?,qty=? "+" ,total=? WHERE aid=?";
                ps=con.prepareStatement(UpdateQuery);
                  ps.setString(1, txt_name.getText());
                    ps.setString(2, txt_province.getText());
                    ps.setString(3, txt_product.getText());
                    ps.setString(4, txt_grade.getText());
                     ps.setString(5, txt_amount.getText());
                 ps.setString(6, txt_qty.getText());
                    ps.setString(7, txt_total.getText());
                    ps.setInt(8, Integer.parseInt(txt_id.getText()));
                     ps.executeUpdate();
                     Show_employee();
                
                JOptionPane.showMessageDialog(null, "Product Updated");
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Mofa.class.getName()).log(Level.SEVERE, null, ex);
            }

    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int index=jTable1.getSelectedRow();
         ShowEmployee(index);

        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         this.dispose();
             new Home().setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //float price=Float.parseFloat(txt_amount.getText());
        //float qty=Float.parseFloat(txt_qty.getText());
        //float total=price*qty;
        
        float value = Float.parseFloat(txt_amount.getText())*Float.parseFloat(txt_qty.getText());
        txt_total.setText(String.valueOf(value));
         //jLable10.settext(String.valueof(value));
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!txt_id.getText().equals("")){
            try {
                Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("DELETE FROM mofa_info WHERE aid=?");
                int id=Integer.parseInt(txt_id.getText());
                ps.setInt(1, id);
      
                ps.executeUpdate();
                 Show_employee();
                
                JOptionPane.showMessageDialog(null, "Informations Deleted");
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Employee_Info1.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Infomrmations Not Deleted");
                
                
            }
            
        
        
        
        }else{
            
              JOptionPane.showMessageDialog(null, "Product Not Deleted : No Id to Delete");
              
        
        
        
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
         Grades gd=new Grades();
        gd.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provinceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_provinceActionPerformed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            txt_name.setEditable(true);
        
        }else{
            txt_name.setEditable(false);
            JOptionPane.showMessageDialog(null, "Invalid character");
           
        
        }
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_provinceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provinceKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            txt_province.setEditable(true);
        
        }else{
            txt_province.setEditable(false);
            JOptionPane.showMessageDialog(null, "Invalid character");
           
        
        }
    }//GEN-LAST:event_txt_provinceKeyPressed

    private void txt_productKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            txt_product.setEditable(true);
        
        }else{
            txt_product.setEditable(false);
            JOptionPane.showMessageDialog(null, "Invalid character");
           
        
        }
    }//GEN-LAST:event_txt_productKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mofa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_product;
    private javax.swing.JTextField txt_province;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
