/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.DBconnect;
import Code.Order;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Vihanga
 */
public class OrderDetails extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetails
     */
    
    PreparedStatement pst = null;
    Connection con = null;
    Order o1 = new Order();
    DefaultTableModel model;
    ResultSet rs = null;
    
    public OrderDetails() {
        initComponents();
        con = DBconnect.connect();
        getConnection();
        theader();
        
        o1.fillOrderTable(Otable, "");
        model = (DefaultTableModel) Otable.getModel();
        
        
        AutoCompleteDecorator.decorate(ProductNameComboBox);
        FillComboSupplierBox();
    }
    
      private void FillComboSupplierBox() {
              try{
                    String sql = "SELECT * from product"; 
                    pst = con.prepareStatement(sql);
                    rs=pst.executeQuery();

                    while(rs.next()){

                    String productname = rs.getString("pname");
                    ProductNameComboBox.addItem(productname);
               }
            }
            catch(Exception e){
                     JOptionPane.showConfirmDialog(null,e);
                }
    }
    
    public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itp","root","");
            
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
            
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oaddbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Otable = new javax.swing.JTable();
        oqtybox = new javax.swing.JTextField();
        oidbox = new javax.swing.JTextField();
        oamountbox = new javax.swing.JTextField();
        odatebox = new com.toedter.calendar.JDateChooser();
        oupdate = new javax.swing.JButton();
        odelete = new javax.swing.JButton();
        osearchbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ProductNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 255, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Ordered Product :");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Amount :");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setText("Order Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Order ID :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Quantity :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Order Date :");

        oaddbutton.setBackground(new java.awt.Color(8, 88, 8));
        oaddbutton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        oaddbutton.setForeground(new java.awt.Color(255, 255, 255));
        oaddbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        oaddbutton.setText("Insert");
        oaddbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oaddbutton.setBorderPainted(false);
        oaddbutton.setIconTextGap(10);
        oaddbutton.setPreferredSize(new java.awt.Dimension(150, 35));
        oaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oaddbuttonActionPerformed(evt);
            }
        });

        Otable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Otable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Otable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Ordered Product", "Order Date", "Quntity", "Amount"
            }
        ));
        Otable.setRowHeight(25);
        Otable.setRowMargin(3);
        Otable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OtableMouseClicked(evt);
            }
        });
        Otable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OtableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Otable);

        oqtybox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        oqtybox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        oqtybox.setPreferredSize(new java.awt.Dimension(250, 40));
        oqtybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oqtyboxActionPerformed(evt);
            }
        });

        oidbox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        oidbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        oidbox.setPreferredSize(new java.awt.Dimension(250, 40));
        oidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oidboxActionPerformed(evt);
            }
        });

        oamountbox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        oamountbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        oamountbox.setPreferredSize(new java.awt.Dimension(250, 40));
        oamountbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oamountboxActionPerformed(evt);
            }
        });

        odatebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        odatebox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        odatebox.setPreferredSize(new java.awt.Dimension(250, 40));

        oupdate.setBackground(new java.awt.Color(0, 0, 102));
        oupdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        oupdate.setForeground(new java.awt.Color(255, 255, 255));
        oupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        oupdate.setText("Update");
        oupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oupdate.setBorderPainted(false);
        oupdate.setIconTextGap(10);
        oupdate.setPreferredSize(new java.awt.Dimension(150, 35));
        oupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oupdateActionPerformed(evt);
            }
        });

        odelete.setBackground(new java.awt.Color(162, 11, 11));
        odelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        odelete.setForeground(new java.awt.Color(255, 255, 255));
        odelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        odelete.setText("Delete");
        odelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        odelete.setBorderPainted(false);
        odelete.setIconTextGap(10);
        odelete.setPreferredSize(new java.awt.Dimension(150, 35));
        odelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odeleteActionPerformed(evt);
            }
        });

        osearchbox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        osearchbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        osearchbox.setPreferredSize(new java.awt.Dimension(250, 40));
        osearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osearchboxActionPerformed(evt);
            }
        });
        osearchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                osearchboxKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Search Order :");

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left-arrow.png"))); // NOI18N
        jButton1.setText("Back to Stock Management Main");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loupe.png"))); // NOI18N

        ProductNameComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        ProductNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product in Stock" }));
        ProductNameComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ProductNameComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(oupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oaddbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(odelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel6)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(odatebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(oqtybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(oamountbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(ProductNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(oidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(osearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(odatebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oqtybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oamountbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(oaddbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(odelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean verifText()
    {
        
        if      (oidbox.getText().equals("")
                ||ProductNameComboBox.getSelectedItem().equals("Select Product in Stock")
                ||oqtybox.getText().equals("")
                ||oamountbox.getText().equals("")
                ||odatebox.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"One or More Field Empty.");
            return false;
        }
 
        else
        {
            return true;
        }
        
            
    }
    
    private void theader(){
        JTableHeader thead = Otable.getTableHeader();
        thead.setForeground(Color.BLACK);
        thead.setFont(new Font("Tahome",Font.BOLD, 14));
        
    }
    
    private void oidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oidboxActionPerformed

    private void oqtyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oqtyboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oqtyboxActionPerformed

    private void oaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oaddbuttonActionPerformed
          String oid = oidbox.getText();
          //String oproduct = oproductbox.getText();
          String productName = ProductNameComboBox.getSelectedItem().toString();
          String oqty = oqtybox.getText();
          String oamount = oamountbox.getText();
          
          if(verifText()){
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String odate = dateFormat.format(odatebox.getDate());
               
                Order o = new Order();
                o.insertUpdateDeleteOrder('i', oid, productName, odate, oqty, oamount);
                
                OrderDetails.Otable.setModel(new DefaultTableModel(null,new Object[]{"Order ID" , "Ordered Product" , "Order Date" , "Quntity" , "Amount"}));
                o.fillOrderTable(OrderDetails.Otable, "");
          }
          

    }//GEN-LAST:event_oaddbuttonActionPerformed

    private void oupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oupdateActionPerformed
        // TODO add your handling code here:
          String oid = oidbox.getText();
         // String oproduct = oproductbox.getText();
         String productName = ProductNameComboBox.getSelectedItem().toString();
          String oqty = oqtybox.getText();
          String oamount = oamountbox.getText();
          
          if(verifText()){
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String odate = dateFormat.format(odatebox.getDate());
               
                Order o = new Order();
                o.insertUpdateDeleteOrder('u', oid, productName, odate, oqty, oamount);
                OrderDetails.Otable.setModel(new DefaultTableModel(null,new Object[]{"Order ID" , "Ordered Product" , "Order Date" , "Quntity" , "Amount"}));
                o.fillOrderTable(OrderDetails.Otable, "");
          }
        
        
    }//GEN-LAST:event_oupdateActionPerformed

    private void odeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odeleteActionPerformed
        // TODO add your handling code here:
        
        if(oidbox.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Order Selected");
        }
        
        else
        {
            String oid = oidbox.getText();
            Order o = new Order();
            o.insertUpdateDeleteOrder('d', oid, null, null, null, null);
            
            o.fillOrderTable(Otable, "");
            Otable.setModel(new DefaultTableModel(null,new Object[]{"Order ID" , "Ordered Product" , "Order Date" , "Quntity" , "Amount"}));
            o1.fillOrderTable(Otable, osearchbox.getText());
            
            oidbox.setText("");
            ProductNameComboBox.setSelectedItem("");
            oqtybox.setText("");
            oamountbox.setText("");
            odatebox.setDate(null);
        }
    }//GEN-LAST:event_odeleteActionPerformed

    int rowIndex;
    private void OtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OtableMouseClicked
        // TODO add your handling code here:
        
        rowIndex = Otable.getSelectedRow();
        
        
        oidbox.setText(model.getValueAt(rowIndex, 0).toString());
        //oproductbox.setText(model.getValueAt(rowIndex, 1).toString());
        ProductNameComboBox.setSelectedItem(model.getValueAt(rowIndex, 1).toString());
        oqtybox.setText(model.getValueAt(rowIndex, 3).toString());
        oamountbox.setText(model.getValueAt(rowIndex, 4).toString());
        
            Date odate;
        
       
        try 
        {
            odate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 2).toString());
             odatebox.setDate(odate);
        } 
        
        catch (ParseException ex) 
        {
            Logger.getLogger(OrderDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          
            
    }//GEN-LAST:event_OtableMouseClicked

    private void osearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osearchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osearchboxActionPerformed

    private void osearchboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_osearchboxKeyTyped
        // TODO add your handling code here:
        Otable.setModel(new DefaultTableModel(null,new Object[]{"Order ID" , "Ordered Product" , "Order Date" , "Quntity" , "Amount"}));
        o1.fillOrderTable(Otable, osearchbox.getText());
    }//GEN-LAST:event_osearchboxKeyTyped

    private void OtableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtableKeyPressed
        
        
    }//GEN-LAST:event_OtableKeyPressed

    private void OtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtableKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN )
        {
            
            rowIndex = Otable.getSelectedRow();
        
        
            oidbox.setText(model.getValueAt(rowIndex, 0).toString());
           // oproductbox.setText(model.getValueAt(rowIndex, 1).toString());
            ProductNameComboBox.setSelectedItem(model.getValueAt(rowIndex, 1).toString());
            oqtybox.setText(model.getValueAt(rowIndex, 3).toString());
            oamountbox.setText(model.getValueAt(rowIndex, 4).toString());
            
            
            Date odate;
                try 
                    {
                        odate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 2).toString());
                         odatebox.setDate(odate);
                    } 
        
                catch (ParseException ex) 
                    {
                        Logger.getLogger(OrderDetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }
    }//GEN-LAST:event_OtableKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StockManagementMain sm = new StockManagementMain();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oamountboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oamountboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oamountboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Otable;
    private javax.swing.JComboBox<String> ProductNameComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton oaddbutton;
    private javax.swing.JTextField oamountbox;
    private com.toedter.calendar.JDateChooser odatebox;
    private javax.swing.JButton odelete;
    private javax.swing.JTextField oidbox;
    private javax.swing.JTextField oqtybox;
    private javax.swing.JTextField osearchbox;
    private javax.swing.JButton oupdate;
    // End of variables declaration//GEN-END:variables
}
