/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.DBconnect;
import Code.Product;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Vihanga
 */
public class ProductDetails extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetails
     */
    
    Product p1 = new Product();
    DefaultTableModel model;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public ProductDetails() {
        

        initComponents();
        //getConnection();
        con = DBconnect.connect();
        theader();
        p1.fillProductTable(ptable, "");
        model = (DefaultTableModel) ptable.getModel();
        
         //Autocomplete supplier ComboBox
        AutoCompleteDecorator.decorate(SupplierNameComboBox);
        FillComboSupplierBox();
        

    }
    
    private void FillComboSupplierBox(){
            try{
                    String sql = "SELECT * from supplier"; 
                    pst = con.prepareStatement(sql);
                    rs=pst.executeQuery();

                    while(rs.next()){

                    String suppliername = rs.getString("sname");
                    SupplierNameComboBox.addItem(suppliername);
               }
            }
            catch(Exception e){
                        JOptionPane.showConfirmDialog(null,e);
                }
    }
    
    public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itp","root","");
            
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
           
            return null;
        }
    }
    
    private void theader(){
        JTableHeader thead = ptable.getTableHeader();
        thead.setForeground(Color.BLACK);
        thead.setFont(new Font("Tahome",Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oaddbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        pnamebox = new javax.swing.JTextField();
        pidbox = new javax.swing.JTextField();
        pqtybox = new javax.swing.JTextField();
        ppricebox = new javax.swing.JTextField();
        pexpdatebox = new com.toedter.calendar.JDateChooser();
        pmanudatebox = new com.toedter.calendar.JDateChooser();
        pupdate = new javax.swing.JButton();
        pdelete = new javax.swing.JButton();
        psearch = new javax.swing.JTextField();
        psearchbox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        SupplierNameComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(180, 255, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setText("Product Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Product ID :");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Manufacture Date :");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Expiry Date :");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Product Name :");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Price :");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Quantity :");
        jLabel7.setToolTipText("");

        oaddbutton.setBackground(new java.awt.Color(8, 88, 8));
        oaddbutton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        oaddbutton.setForeground(new java.awt.Color(255, 255, 255));
        oaddbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        oaddbutton.setText("Insert");
        oaddbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oaddbutton.setBorderPainted(false);
        oaddbutton.setIconTextGap(10);
        oaddbutton.setPreferredSize(new java.awt.Dimension(150, 35));
        oaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oaddbuttonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setText("Supplier Name :");
        jLabel9.setToolTipText("");

        ptable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ptable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product", "Manu. Date", "Expiry Date", "Price", "Quantity", "Supplier"
            }
        ));
        ptable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ptable.setRowHeight(25);
        ptable.setRowMargin(3);
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        ptable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        pnamebox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        pnamebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnamebox.setPreferredSize(new java.awt.Dimension(250, 40));
        pnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameboxActionPerformed(evt);
            }
        });

        pidbox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        pidbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pidbox.setPreferredSize(new java.awt.Dimension(250, 40));
        pidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidboxActionPerformed(evt);
            }
        });

        pqtybox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        pqtybox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pqtybox.setPreferredSize(new java.awt.Dimension(250, 40));
        pqtybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pqtyboxActionPerformed(evt);
            }
        });
        pqtybox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pqtyboxKeyTyped(evt);
            }
        });

        ppricebox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        ppricebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ppricebox.setPreferredSize(new java.awt.Dimension(250, 40));
        ppricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppriceboxActionPerformed(evt);
            }
        });

        pexpdatebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pexpdatebox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        pexpdatebox.setPreferredSize(new java.awt.Dimension(250, 40));

        pmanudatebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pmanudatebox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        pmanudatebox.setPreferredSize(new java.awt.Dimension(250, 40));

        pupdate.setBackground(new java.awt.Color(0, 0, 102));
        pupdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pupdate.setForeground(new java.awt.Color(255, 255, 255));
        pupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        pupdate.setText("Update");
        pupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pupdate.setBorderPainted(false);
        pupdate.setIconTextGap(10);
        pupdate.setPreferredSize(new java.awt.Dimension(150, 35));
        pupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdateActionPerformed(evt);
            }
        });

        pdelete.setBackground(new java.awt.Color(162, 11, 11));
        pdelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pdelete.setForeground(new java.awt.Color(255, 255, 255));
        pdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        pdelete.setText("Delete");
        pdelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pdelete.setBorderPainted(false);
        pdelete.setIconTextGap(10);
        pdelete.setPreferredSize(new java.awt.Dimension(150, 35));
        pdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdeleteActionPerformed(evt);
            }
        });

        psearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        psearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        psearch.setPreferredSize(new java.awt.Dimension(250, 40));
        psearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psearchActionPerformed(evt);
            }
        });
        psearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psearchKeyPressed(evt);
            }
        });

        psearchbox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        psearchbox.setText("Search Product :");

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left-arrow.png"))); // NOI18N
        jButton1.setText("Back to Stock Management Main");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loupe.png"))); // NOI18N

        SupplierNameComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        SupplierNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Supplier" }));
        SupplierNameComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SupplierNameComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        jButton3.setBackground(new java.awt.Color(0, 51, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/statistics.png"))); // NOI18N
        jButton3.setText("Generate Report");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.setIconTextGap(10);
        jButton3.setPreferredSize(new java.awt.Dimension(150, 35));

        jButton2.setBackground(new java.awt.Color(0, 51, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gmail.png"))); // NOI18N
        jButton2.setText("Send Email");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setIconTextGap(10);
        jButton2.setPreferredSize(new java.awt.Dimension(150, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(180, 255, 150));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(57, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(psearchbox)
                        .addGap(18, 18, 18)
                        .addComponent(psearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel2)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnamebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pmanudatebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pexpdatebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppricebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pqtybox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pidbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SupplierNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oaddbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(psearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(psearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2))
                            .addComponent(pidbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(pmanudatebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(pexpdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(ppricebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(pqtybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(oaddbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean verifText()
    {
        
        if      (pidbox.getText().equals("")||pnamebox.getText().equals("")
                ||ppricebox.getText().equals("")||pqtybox.getText().equals("")
                //||psupnamebox.getText().equals("") 
                || SupplierNameComboBox.getSelectedItem().equals("Select")
                || pmanudatebox.getDate() == null 
                || pexpdatebox.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"One or More Field Empty.");
            return false;
        }
        //choose manufacture date higher than the current date
        else if (pmanudatebox.getDate().compareTo(new Date ()) > 0)
        {
            JOptionPane.showMessageDialog(null,"Manufacture Date Higher Than The Current Date.");
            return false;
        }
        
        else if (pmanudatebox.getDate().compareTo(pexpdatebox.getDate()) > 0)
        {
            JOptionPane.showMessageDialog(null,"Manufacture Date Higher Than The Expiery Date.");
            return false;
        }
        
     
        
        else
        {
            return true;
        }
        
            
    }
    
    
    private void oaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oaddbuttonActionPerformed
          String pid = pidbox.getText();
          String pname = pnamebox.getText();
          String pprice = ppricebox.getText();
          String pqty = pqtybox.getText();
          //String psupname = psupnamebox.getText();
          String supName = SupplierNameComboBox.getSelectedItem().toString();
          
          if(verifText()){
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String pmanudate = dateFormat.format(pmanudatebox.getDate());
                String pexpdate = dateFormat.format(pexpdatebox.getDate());
                Product p = new Product();
                //p.insertUpdateDeleteProduct('i', pid, pname, pmanudate, pexpdate, pprice, pqty, psupname);
                p.insertUpdateDeleteProduct('i', pid, pname, pmanudate, pexpdate, pprice, pqty, supName);
                
                ProductDetails.ptable.setModel(new DefaultTableModel(null,new Object[]{"Product ID" , "Product" , "Manu. Date" , "Expiry Date", "Price", "Quntity", "Supplier" }));
                p.fillProductTable(ProductDetails.ptable, "");
                
                clearTextBoxes();
          }
          
          
          
          
          
          
          
          

    }//GEN-LAST:event_oaddbuttonActionPerformed

    private void pnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameboxActionPerformed

    private void pidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidboxActionPerformed

    private void pqtyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqtyboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pqtyboxActionPerformed

    private void ppriceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppriceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppriceboxActionPerformed

    private void pqtyboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqtyboxKeyTyped
   
    }//GEN-LAST:event_pqtyboxKeyTyped

    public void clearTextBoxes() {
         pidbox.setText("");
         pnamebox.setText("");
         ppricebox.setText("");
         pqtybox.setText("");
         pmanudatebox.setDate(null);
         pexpdatebox.setDate(null);
         SupplierNameComboBox.setSelectedItem("Choose Supplier");
    }
    
    private void pupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdateActionPerformed
        // TODO add your handling code here:
        
          String pid = pidbox.getText();
          String pname = pnamebox.getText();
          String pprice = ppricebox.getText();
          String pqty = pqtybox.getText();
          //String psupname = psupnamebox.getText();
          String supName = SupplierNameComboBox.getSelectedItem().toString();
          
          if(verifText()){
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String pmanudate = dateFormat.format(pmanudatebox.getDate());
                String pexpdate = dateFormat.format(pexpdatebox.getDate());
                
                Product p = new Product();
                //p.insertUpdateDeleteProduct('u', pid, pname, pmanudate, pexpdate, pprice, pqty, psupname);
                p.insertUpdateDeleteProduct('u', pid, pname, pmanudate, pexpdate, pprice, pqty, supName);
                
                ProductDetails.ptable.setModel(new DefaultTableModel(null,new Object[]{"Product ID" , "Product" , "Manu. Date" , "Expiry Date", "Price", "Quntity", "Supplier" }));
                p.fillProductTable(ProductDetails.ptable, "");
                
                clearTextBoxes();
                
          }
    }//GEN-LAST:event_pupdateActionPerformed

    private void pdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdeleteActionPerformed
        // TODO add your handling code here:
        
        if(pidbox.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Product Selected");
        }
        
        else
        {
            String pid = pidbox.getText();
            Product p = new Product();
            p.insertUpdateDeleteProduct('d', pid, null, null, null, null, null, null);
            p.fillProductTable(ptable, "");
            ptable.setModel(new DefaultTableModel(null,new Object[]{"Product ID" , "Product" , "Manu. Date" , "Expiry Date", "Price", "Quntity", "Supplier" }));
            p1.fillProductTable(ptable, psearch.getText());
            
            pidbox.setText("");
            pnamebox.setText("");
            ppricebox.setText("");
            pqtybox.setText("");
            SupplierNameComboBox.setSelectedItem("");
            pmanudatebox.setDate(null);
            pexpdatebox.setDate(null);
        }
    }//GEN-LAST:event_pdeleteActionPerformed

    int rowIndex;
    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
        // TODO add your handling code here:
        
        rowIndex = ptable.getSelectedRow();
       
        
        pidbox.setText(model.getValueAt(rowIndex, 0).toString());
        pnamebox.setText(model.getValueAt(rowIndex, 1).toString());
        ppricebox.setText(model.getValueAt(rowIndex, 4).toString());
        pqtybox.setText(model.getValueAt(rowIndex, 5).toString());
        //psupnamebox.setText(model.getValueAt(rowIndex, 6).toString());
         SupplierNameComboBox.setSelectedItem(model.getValueAt(rowIndex, 6).toString());
        
        Date manudate , expdate;
        
        try {
            manudate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 2).toString());
            expdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 3).toString());
            
            pmanudatebox.setDate(manudate);
            pexpdatebox.setDate(expdate);
            
            
        } catch (ParseException ex) {
            Logger.getLogger(ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_ptableMouseClicked

    private void psearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psearchActionPerformed

    private void psearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psearchKeyPressed
        // TODO add your handling code here:
        ptable.setModel(new DefaultTableModel(null,new Object[]{"Product ID" , "Product" , "Manu. Date" , "Expiry Date", "Price", "Quntity", "Supplier" }));
        p1.fillProductTable(ptable, psearch.getText());
    }//GEN-LAST:event_psearchKeyPressed

    private void ptableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptableKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN )
        {
            
            rowIndex = ptable.getSelectedRow();
            pidbox.setText(model.getValueAt(rowIndex, 0).toString());
            pnamebox.setText(model.getValueAt(rowIndex, 1).toString());
            ppricebox.setText(model.getValueAt(rowIndex, 4).toString());
            pqtybox.setText(model.getValueAt(rowIndex, 5).toString());
           // psupnamebox.setText(model.getValueAt(rowIndex, 6).toString());
           SupplierNameComboBox.setSelectedItem(model.getValueAt(rowIndex, 6).toString());
            
                    Date manudate , expdate;

                try {
                    manudate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 2).toString());
                    expdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 3).toString());

                    pmanudatebox.setDate(manudate);
                    pexpdatebox.setDate(expdate);


                } catch (ParseException ex) {
                    Logger.getLogger(ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_ptableKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StockManagementMain sm = new StockManagementMain();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SendEmail se = new SendEmail();
        se.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clearTextBoxes();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SupplierNameComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton oaddbutton;
    private javax.swing.JButton pdelete;
    private com.toedter.calendar.JDateChooser pexpdatebox;
    private javax.swing.JTextField pidbox;
    private com.toedter.calendar.JDateChooser pmanudatebox;
    private javax.swing.JTextField pnamebox;
    private javax.swing.JTextField ppricebox;
    private javax.swing.JTextField pqtybox;
    private javax.swing.JTextField psearch;
    private javax.swing.JLabel psearchbox;
    public static javax.swing.JTable ptable;
    private javax.swing.JButton pupdate;
    // End of variables declaration//GEN-END:variables
}
